### ISSUE TITLE
The load component throws Rate Transition warnings when on CPL mode

### ISSUE THREAD

**Issue by murilones** [typhoon-hil/opendss-typhoon-hil-interface#58]
During compilation the following warning is raised:

_RateTransitionWarning: Input and output execution rate of Rate Transition component 'Load1.CPL.Rate Transition2' should not be the same. This can cause unexpected results._ 

This should be verified since the rate transition might not be needed or is configured incorrectly.

**Comment by NavidA1** [comment]
Pushed an update to address this issue.
- new auxiliary component named "Rate Transition with Bypass" added and is used instead of core library rate transition. This component switches to a unit delay when its bypass flag is activated.
- Required code added to component masks to use the bypass flag when slow and fast execution rates are equal. (including Single-phase CPL, CPL and load components)

Compiling with equal transition rates no longer generate a warning.
